# Alte Adresse digital.lesenundschenken.de -> lesen.lesenundschenken.de.
# Ablage:  /var/www/vhosts/system/digital.lesenundschenken.de/conf/vhost_ssl.conf
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_URI} ^/(\.well-known|plesk-stat|webstat|webstat-ssl|ftpstat|error_docs)(/|$) [NC]
    RewriteRule ^ - [L]
    RewriteRule ^/?(.*)$ https://lesen.lesenundschenken.de/$1 [R=301,QSA,L]
</IfModule>
